// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace kafka
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class KafkaMessage : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"KafkaMessage\",\"namespace\":\"kafka\",\"fields\":[{\"name\":\"Id\"" +
				",\"type\":\"string\"},{\"name\":\"Key\",\"type\":\"string\"},{\"name\":\"Topic\",\"type\":\"string\"" +
				"},{\"name\":\"Partition\",\"type\":\"int\"}]}");
		private string _Id;
		private string _Key;
		private string _Topic;
		private int _Partition;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return KafkaMessage._SCHEMA;
			}
		}
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public string Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				this._Key = value;
			}
		}
		public string Topic
		{
			get
			{
				return this._Topic;
			}
			set
			{
				this._Topic = value;
			}
		}
		public int Partition
		{
			get
			{
				return this._Partition;
			}
			set
			{
				this._Partition = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Key;
			case 2: return this.Topic;
			case 3: return this.Partition;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.Key = (System.String)fieldValue; break;
			case 2: this.Topic = (System.String)fieldValue; break;
			case 3: this.Partition = (System.Int32)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
